// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhkdhsymwrtpmgjsmqqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoa2Roc3ltd3J0cG1nanNtcXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTcyNjUsImV4cCI6MjA3MDc3MzI2NX0.7AibcBDojR2hTiEZpAaZgb6nvnZkzHBLsCO0yTsTJ18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});